# Generated by Django 4.2.6 on 2023-10-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CPALink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('background_image', models.ImageField(upload_to='cpa_links/background_images/')),
                ('product_image', models.ImageField(upload_to='cpa_links/product_images/')),
                ('text_link', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cpacategory')),
            ],
        ),
    ]
