# Generated by Django 4.2.6 on 2023-10-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_cpacategory_cpalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpalink',
            name='title_image',
            field=models.ImageField(default=1, upload_to='cpa_links/title_images/'),
            preserve_default=False,
        ),
    ]
