# Generated by Django 4.2.6 on 2023-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_cpalink_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpalink',
            name='text_link',
        ),
        migrations.AddField(
            model_name='cpalink',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpalink',
            name='text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
