# Generated by Django 4.2.6 on 2023-10-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_cpalink_text_link_cpalink_link_cpalink_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpalink',
            name='button_text',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpalink',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
