# Generated by Django 4.2.6 on 2023-10-05 09:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_cpalink_button_text_cpalink_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpalink',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
    ]
